services:
  snippet-manager:
    image: ghcr.io/ingsis-group-11/snippet-manager:latest
    ports:
      - "8000:8080"
    depends_on:
      - db-snippet
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/snippet-manager-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
  db-snippet:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=snippet-manager-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  printscript-service:
    image: ghcr.io/ingsis-group-11/printscript-service:latest
    ports:
      - "8004:8080"
  permission-manager:
    image: ghcr.io/ingsis-group-11/permission-manager:latest
    ports:
      - "8003:8080"
    depends_on:
      - db-permissions
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5433/permission-manager-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
  db-permissions:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=permission-manager-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
volumes:
  postgres_data: